version: "3.9"

services:
  agent:
    build:
      context: ./agent
    container_name: remna-agent
    restart: always
    network_mode: host
    environment:
      AGENT_NAME: ${AGENT_NAME}
      AGENT_TOKEN: ${AGENT_TOKEN}

  bot:
    build:
      context: ./bot
    container_name: remna-bot
    restart: always
    network_mode: host
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      AGENT_TOKEN: ${AGENT_TOKEN}
      AGENTS: ${AGENTS}
